### ISSUE TITLE
数组越界和空指针crash捕捉不到

### ISSUE THREAD

**Issue by kongtianxintang** [xiaoyi6409/XYCrashManager#1]
数组越界和空指针crash捕捉不到,是不是我打开的方式不对？
//数组越界
let list = [2,1]
let _ = list[3];
//空指针
var str:String?
print(str!)

**Comment by kongtianxintang** [comment]
抱歉～才发现在debug模式下xcode会优先获取到错误信息～打扰了

**Comment by NiceShock** [comment]
swift5是真捕获不到了

**Comment by kongtianxintang** [comment]
> swift5是真捕获不到了

那就很尴尬了
